[config]

[templates]

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/theme.rasi"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.conf'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.niri]
input_path = "~/.config/matugen/templates/niri.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.foot]
input_path = "~/.config/matugen/templates/foot.ini"
output_path = "~/.config/foot/themes/matugen.ini"

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.avizo]
input_path = '~/.config/matugen/templates/avizo.ini'
output_path = '~/.config/avizo/config.ini'

# [templates.vicinae]
# input_path = '~/.config/matugen/templates/vicinae.toml'
# output_path = '~/.local/share/vicinae/themes/matugen.toml'
# post_hook = 'vicinae theme set matugen'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook =   'pkill -USR2 btop'