[colors.primary]
background = '#11131c'
foreground = '#e2e1ee'
 
[colors.cursor]
text = '#e2e1ee'
cursor = '#c4c5d8' 
 
[colors.vi_mode_cursor]
text = '#11131c'
cursor = '#b8c3ff' 
 
[colors.search.matches]
foreground = '#434656' 
background = '#f6adff' 
 
[colors.search.focused_match]
foreground = '#434656' 
background = '#b8c3ff' 
 
[colors.footer_bar]
foreground = '#434656' 
background = '#e2e1ee' 
 
[colors.hints.start]
foreground = '#434656' 
background = '#b8c3ff' 
 
[colors.hints.end]
foreground = '#434656' 
background = '#b8c3ff' 
 
[colors.selection]
text = '#11131c'
background = '#b8c3ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#b8c3ff' 
yellow = '#184beb' 
blue = '#b8c3ff' 
magenta = '#f6adff' 
cyan = '#b8c3ff' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 